---
# this role manages nagios monitoring
- name: install nagios
  yum: name=nagios state=present

- name: start nagios
  service: name=nagios state=started

# nagios checks
- name: redmine status check
  copy: src=checks/check_redmine.rb dest=/usr/lib64/nagios/plugins/check_redmine
        mode=0755 owner=root
