---
# this role manages nagios monitoring
- name: install nagios
  yum: name=nagios state=present

- name: start nagios
  service: name=nagios state=started

# nagios configuration of checks to run
- name: localhost.cfg
  copy: src=config/localhost.cfg dest=/etc/nagios/objects/localhost.cfg
        mode=0664 owner=nagios
- name: commands.cfg
  copy: src=config/commands.cfg dest=/etc/nagios/objects/commands.cfg
        mode=0664 owner=nagios

# nagios checks
- name: redmine status check
  copy: src=checks/check_redmine.rb dest=/usr/lib64/nagios/libexec/check_redmine
        mode=0755 owner=root
- name: denyhosts status check
  copy: src=checks/check_denyhosts.rb dest=/usr/lib64/nagios/libexec/check_denyhosts
        mode=0755 owner=root
