---
# all hosts inherit the common role
- hosts: all
  gather_facts: no
  roles:
  - common
  - { role: ansible, sudo: yes }

# these are things that only run on zubkoland.org
- hosts: localhost
  gather_facts: no
  roles:
  - { role: dotfiles, user: djanatyn }
  - { role: web, sudo: yes }
