# these are things that only run on zubkoland.org
- hosts: localhost
  connection: local # we need this for fast file io
  gather_facts: no
  sudo: yes
  roles:
  - { role: dotfiles }
  - { role: common }
