# these are things that only run on zubkoland.org
- hosts: localhost
  connection: local # we need this for fast file io
  gather_facts: no
  sudo: yes
  roles:
  - { role: ansible-users, users_default_shell: /bin/zsh }
  - { role: dotfiles}
  - { role: web, tags: ['web'] }
  - { role: mail, tags: ['mail'] }
  - { role: scripts, tags: ['scripts'] }
  - { role: users }
  - { role: redmine }
  - { role: nagios }
  - { role: whalespeak, tags: ['whalespeak'] }
