---
# this role is for meta stuff, like managing zubkoland's ansible 
# configuration.
#
# the config is stored in /var/local/ansible/ and we update that directory
# whenever new changes are added; /usr/local/bin/update_zubkoland runs the
# playbook after updating the repository.

- copy: src=update_development.sh dest=/usr/local/bin/update_development mode=0755
