---
# this playbook manages mail on zubkoland.org
- name: update postifx configuration file
  copy: dest=/etc/postfix/main.cf src=postfix_main.cf
        mode=0644 owner=root force=yes

- name: update maildrop configuration
  copy: dest=/etc/maildroprc src=maildroprc
        mode=0644 owner=root force=yes

- name: update aliases for mailing list
  copy: path=/etc/aliases src=aliases
        mode=0644 owner=root force=no
