---
# this playbook manages mail on zubkoland.org
- name: update postifx configuration file
  file: path=/etc/postfix/main.cf src=postfix_main.cf
        mode=0644 owner=root

- name: update maildrop configuration
  file: path=/etc/maildroprc src=maildroprc
        mode=0644 owner=root
