---
# this role is for plays on all hosts i own
# these tasks are excecuted on all hosts!

# these packages get installed everywhere
- name: install basic packages
  yum: name={{ item }} state=present
  with_items:
    - weechat
    - zsh
    - htop

- name: install gems for development
  gem: name={{ item }} state=present
  with_items:
    - pry
