---
- name: install user packages
  dnf: name={{ item }} state=present
  with_items:
    - weechat
    - zsh
    - htop
    - tmux

- name: install development packages
  dnf: name={{ item }} state=present
  with_items:
    - jq
    - tig
    - go

- name: install build packages
  dnf: name={{ item }} state=present
  with_items:
    - automake
    - ncurses-devel
    - openssl-devel
    - libyaml-devel
    - gettext-devel
    - libxml++-devel
    - libcurl-devel

- name: install system tools
  dnf: name={{ item }} state=present
  with_items:
    - nmap-ncat
    - procps
    - pwgen
    - tar
    - xz
    - wget
    - curl
    - man
    - bind-utils
    - pinentry

- name: install mail packages
  dnf: name={{ item }} state=present
  with_items: ['offlineimap', 'msmtp']

- name: install python packages
  pip: name={{ item }} state=present
  with_items: ['virtualenvwrapper']
